### ISSUE TITLE
Release gem with relaxed `nokogiri` dependency

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-bib#10]
`relaton-bib`'s tests passed with `nokogiri "~1.10"`

 @opoudjis may I ask you for help with releasing `relaton-bib`, no rush

_Originally posted by @CAMOBAP795 in https://github.com/metanorma/metanorma-build-scripts/issues/18#issuecomment-513453195_

**Comment by ronaldtse** [comment]
Or @andrew2net , could you help release the gem? Thanks!

**Comment by andrew2net** [comment]
@ronaldtse yes, sure
