### ISSUE TITLE
docid leniency in Hash

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton-bib#25]
Now that the outside world is starting to use Asciibib/Relaton YAML, they are finding it difficult to provide all the detail that is required.

docid is currently expected to be a hash of :type and :id 

@ronaldtse requests that when docid is provided as just a string, that it be coerced into a hash of type = "" and id = the string; i.e.

docid:: X

be treated as

docid:: {type: "", id: "X"}

**Comment by andrew2net** [comment]
@opoudjis actually the `docid` is an `Array` of `Hash`.
It's not clear to me what changes should be done.

**Comment by opoudjis** [comment]
If docid is given a single Hash argument, it is coerced into an array of Hash, with a single member.

If docid is given a single *string* argument, it is to be coerced to a an array with a single Hash member with empty type.

So a request for:

docid:: "X"

is to be realised as:

{docid: [ {type: "", id: "X"} ]

This is a recurring pattern with AsciiBib parsing, which we have already encountered: the types may natively be arrays or hashes or both, but we want them to produce sensible output when they are given just a string value. And in the case of AsciiBib, those structures are being provided by end users (such as @ronaldtse  :-) ), so we expect to see bare strings supplied as values a lot.
