### ISSUE TITLE
Trim XML data by language

### ISSUE THREAD

**Issue by andrew2net** [relaton/relaton-bib#31]
To solve this issue https://github.com/metanorma/metanorma-iso/issues/417#issuecomment-702239754 it needs to add `:lang` option to `.to_xml` method. So calling `.to_xml(lang: "fr")` trims all non French language tagged strings from XML.

**Comment by opoudjis** [comment]
Does not seem to be filtering out "en" titles if "fr" requested, is doing both. I am using `.fetch(lang: "fr")`, don't know if that makes a difference.

**Comment by andrew2net** [comment]
When we fetch ISO we have to get "en" page in any case, because we need to get the links to pages in other languages from the page. So if you fetch "fr" you get "en" and "fr". The fetch method returns BibliographicItem instance which contains all fetched languages. You need use ".to_xml(:lang => "fr")" to get filtered XML
