### ISSUE TITLE
Not all bibliographic dates have year granularity

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton-bib#34]
https://github.com/metanorma/metanorma-ietf/issues/98 points out that they are entering dates in Asciibib with month and day granularity, and the Asciibib processor is truncating them to years (at `.to_xml`); e.g.

````
#<RelatonBib::BibliographicItem:0x00007fe08d9bee00
...
@date=[#<RelatonBib::BibliographicDate:0x00007fe08d9be7e8 @type="issued", @on=#<Date: 2014-01-01 ((2456659j,0s,0n),+0s,2299161j)>, @from=nil, @to=nil>, #<RelatonBib::BibliographicDate:0x00007fe08d9be270 @type="published", @on=nil, @from=#<Date: 2014-04-01 ((2456749j,0s,0n),+0s,2299161j)>, @to=#<Date: 2014-05-01 ((2456779j,0s,0n),+0s,2299161j)>>, #<RelatonBib::BibliographicDate:0x00007fe08d9bdd48 @type="accessed", @on=#<Date: 2015-05-20 ((2457163j,0s,0n),+0s,2299161j)>, @from=nil, @to=nil>],
....
````

is being serialised as:

````
<bibitem id=\"TC211\" type=\"standard\">\n 
...
  <date type=\"issued\">\n    <on>2014</on>\n  </date>\n
<date type=\"published\">\n    <from>2014</from>\n    <to>2014</to>\n  </date>\n  
````

If a date is entered by users at month or day granularity, in AsciiBib via Hash, or in XML source, it should be output to XML in the same granularity.

Regrettably, that means you can't just use ruby Date; I presume you will need to preserve a granularity setting for each date processed...

**Comment by andrew2net** [comment]
The `to_xml` method has a date format option https://github.com/relaton/relaton-bib#date-format
Could it solve this issue?

**Comment by opoudjis** [comment]
As discussed, no, because granularity can vary within a single record.

**Comment by ronaldtse** [comment]
Hoping this can be resolved soon, thanks @andrew2net @opoudjis

**Comment by opoudjis** [comment]
Andrej's fix confirmed as working. Now it's working a little too well: months are being preserved in fetches from relaton, where they were not expected.  Will adjust behaviour of standoc consuming such references, to truncate year where necessary.

**Comment by opoudjis** [comment]
To my pleasant surprised, have anticipated non-year references in NIST and ITU. OGC on the other hand needs to reduce dates to year for rendering.

Having to update relaton-iev to parse such dates received from updated relaton.
