### ISSUE TITLE
Relaton-bib breaking Ruby 3.0

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton-bib#42]
https://github.com/metanorma/metanorma-iso/pull/488/checks?check_run_id=2085701876

````
ArgumentError:
       wrong number of arguments (given 1, expected 0; required keyword: content)
     # ./vendor/bundle/ruby/3.0.0/gems/relaton-bib-1.7.1/lib/relaton_bib/formatted_string.rb:19:in `initialize'
````

This may relate to the ongoing difficulties in compiling this gem with Ruby 3.0. no idea.

**Comment by andrew2net** [comment]
@opoudjis relaton-bib doesn't work with Ruby 3.0 because some dependencies aren't ready for Ruby 3.0.
I've said about it here https://github.com/relaton/support/pull/1#issuecomment-797039633

**Comment by ronaldtse** [comment]
@andrew2net lets get our gems to support ruby 3 and then wait for dependencies (or we have to switch them out).

**Comment by andrew2net** [comment]
@ronaldtse I've updated this gem to support ruby 3 but one of the dependencies `bibtex-ruby` doesn't support ruby 3.
So BibTex functionality doesn't work with ruby 3 now.

**Comment by ronaldtse** [comment]
@andrew2net can you add a check for Ruby version in code, and when bibtex-ruby is "included" throw an error that the BibTex functionality does not support Ruby 3.0 yet? And file a ticket in bibtex-ruby. Thanks!

**Comment by andrew2net** [comment]
@ronaldtse yes, that I've done exactly https://github.com/relaton/relaton-bib/blob/ea64a487ca835f98fc0360f9940b638fc86aef51/lib/relaton_bib/bibtex_parser.rb#L1-L5

**Comment by ronaldtse** [comment]
Thanks! Let’s close this ticket and make a new one for Bibtex support on Ruby 3.

**Comment by andrew2net** [comment]
@ronaldtse should we make a PR in bibtex-ruby gem or will we wait until somebody makes bibtex-ruby works in Ruby 3.0?
