### ISSUE TITLE
(URGENT) relaton-bib crashing Metanorma IETF

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-bib#47]
https://github.com/metanorma/rfc-camelot-holy-grenade/pull/11#issuecomment-853641101

**Comment by ronaldtse** [comment]
Seems to be related to AsciiBib.

**Comment by andrew2net** [comment]
@ronaldtse relaton needs prefix be separated by space to recognize it. I.e. the reference RFC8140 should be RFC 8140.

**Comment by andrew2net** [comment]
fixed in v 1.8.2
