### ISSUE TITLE
Rationalise keys for relaton objects

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton-bib#5]
This ticket is part of the Relaton YAML refactor.

The internal keys for Relaton objects, used in object creation, have until now been used only within the relaton stack, in the scraper routines that extract information from websites.

These internal keys are now being exposed publicly in YAML. Rather than maintain different keys on an ongoing basis, we want the keys to minimise confusion for users, and to be the same keys for YAML and for internal relaton.

There is inconsistency in whether key names are singular or plural: e.g. titles, but docid, notwithstanding that both can have one or multiple instances. This inconsistency is needlessly confusing to end users (not to mention developers), and must be eliminated. All plural key names must become singular.

This impacts the following keys in relaton_bib:

* dates
* titles
* contributors
* relations
* roles
* contacts
* identifiers
* forename
* initial
* addition

**Comment by opoudjis** [comment]
This will break code throughout the relaton stack, and you might even need to treat this as a major release. It will also impact metanorma-standoc, which maps Asciidoctor titles to the `titles` tag.

**Comment by andrew2net** [comment]
@opoudjis In [hash.adoc](https://github.com/metanorma/relaton-bib/blob/master/docs/hash.adoc) you still use plural key names. Should we update the file?

**Comment by andrew2net** [comment]
> This impacts the following keys in relaton_bib:
> * forename
> * initial
> * addition

@opoudjis these keys are singular already. What should we do with them?

**Comment by opoudjis** [comment]
They are singular already, huh. Well, keep them singular. :)

hash.adoc needs to be updated as well.

**Comment by opoudjis** [comment]
Keep this assigned to me after you complete the task and release the gems, @andrew2net; I will need to do downstream changes to metanorma-standoc, and you or I need to update relaton-cli.

**Comment by andrew2net** [comment]
@opoudjis I updated `relaton-cli`
