### ISSUE TITLE
Update grammar to deal with region

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton-bib#55]
I've finally updated the grammar to address https://github.com/relaton/relaton-bib/issues/37

You probably don't need to do a thing, because you'd already implemented it, but just in case, could you please make sure that Relaton aligns with the updated grammar?

**Comment by andrew2net** [comment]
@opoudjis Jing returns errors with the new grammar:
```
[{:column=>23,
  :line=>868,
  :message=>"multiple definitions of \"city\" without \"combine\" attribute",
  :source=>"/Users/andrej/RubyProjects/relaton-bib/grammars/biblio.rng"},
 {:column=>26,
  :line=>878,
  :message=>
   "multiple definitions of \"country\" without \"combine\" attribute",
  :source=>"/Users/andrej/RubyProjects/relaton-bib/grammars/biblio.rng"}]
```

**Comment by opoudjis** [comment]
Ah, ok, I see why. Fixing.

**Comment by andrew2net** [comment]
@opoudjis I see you renamed the second `city` definition. The two `city` definitions were identical. I think it's possible just remove one of them.
The multiple definitions of `country` remain and they are different: `element country { text }` and `element country { RegionType }`. Could you resolve the issue?
