### ISSUE TITLE
citeproc export format

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton-bib#56]
There is a hash format for citations, citeproc, which is used for processing formats like BibTeX, and for processing citations in the CSL library. We wish to implement a serialisation of bibitems with `.to_citeproc`, which will be compatible with such tools.

The format is kind of documented (badly) in https://readthedocs.org/projects/citation-style-language/downloads/pdf/master/ . In the item metadata that citeproc processes, every field of an item is called a "variable", and the variables that the format understands are given in Appendix IV, p. 70.

Variables are standard (strings), numbers, dates, or names; the type of name variables and date variables is given in https://citeproc-js.readthedocs.io/en/latest/csl-json/markup.html?highlight=accessed#name-fields . So dates and names are broken down into hashes and arrays respectively.

The most useful exemplar of what the export should actually look like is given in the to_citeproc functions defined in https://github.com/inukshuk/bibtex-ruby, which export BibTex to that format. Relaton is much more complex than BibTeX, but we don't need the mapping from Relaton to citeproc to be more complex than BibTeX.

So https://github.com/inukshuk/bibtex-ruby/blob/a2b74add5c5597cc193e307478193d1b566a9237/lib/bibtex/names.rb defines the export of names: `{ "family": ... , "given": ..., "suffix": ...., "non-dropping-particle": ... }` (we have not modelled the last yet.)

in https://github.com/inukshuk/bibtex-ruby/blob/a2b74add5c5597cc193e307478193d1b566a9237/lib/bibtex/entry/citeproc_converter.rb

CSL_FIELDS is the variables that the BibTeX parser understands, and they will be the keys to the citeproc has we generate, as defined in the PDF above. Standard types should be mapped to single strings. If the mapping from relaton isn't obvious, leave it (for now): we can always fill out more detail later.

CSL_TYPES correspond to our `bibitem/@type`, with only a little bit of mapping.

**Comment by andrew2net** [comment]
> The most useful exemplar of what the export should actually look like is given in the to_citeproc functions defined in https://github.com/inukshuk/bibtex-ruby, which export BibTex to that format. Relaton is much more complex than BibTeX, but we don't need the mapping from Relaton to citeproc to be more complex than BibTeX.

@opoudjis the bibtex-ruby has an export `to_citeproc`. We use the bibtex-ruby to export BibliographicItem to BibTeX format, so we have a function to create BibTeX::Entry already. I think we can use the bibtex-ruby to render documents in citeproc format. What do you think?

UPD I've tried it and got:
```json
[
  {
    "tile": "Geographic information",
    "edition": "1",
    "author": [
      {
        "family": "Bierman",
        "given": "A."
      },
      {
        "family": "Bierman",
        "given": "Forename"
      }
    ],
    "publisher": "Institute of Electrical and Electronics Engineers",
    "publisher-place": "bib place",
    "note": "note",
    "annote": "An note",
    "howpublished": "How published",
    "comment": "Comment",
    "content": "Table Of Contents",
    "container-title": "Book title",
    "chapter": "4",
    "page": "10-20",
    "volume": "1",
    "accessed": {
      "date-parts": [
        [
          2015,
          5,
          20
        ]
      ]
    },
    "journal": "Journal",
    "issue": "7",
    "collection-title": "RFC",
    "genre": "value",
    "mendeley-tags": "Mendeley Tags",
    "keywords": "Keyword, Key Word",
    "ISBN": "ISBN",
    "lccn": "LCCN",
    "issn": "ISSN",
    "timestamp": "2022-05-02",
    "URL": "https://www.iso.org/standard/53798.html",
    "DOI": "http://standrd.org/doi-123",
    "file2": "file://path/file",
    "month_numeric": "4",
    "id": "ISOTC211",
    "issued": {
      "date-parts": [
        [
          2014,
          4
        ]
      ]
    },
    "type": "misc"
  }
]
```
