### ISSUE TITLE
Support import from BibTeX

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-bib#57]
@andrew2net do we have support for treating a BibTeX file (or files) as a Relaton data source? Thanks.

**Comment by andrew2net** [comment]
@ronaldtse we do https://github.com/relaton/relaton-bib#create-bibliographic-item-from-bibtex

**Comment by ronaldtse** [comment]
Thanks @andrew2net ! Then we just need to implement support for this in Metanorma.

**Comment by andrew2net** [comment]
@ronaldtse can we close this issue?

**Comment by ronaldtse** [comment]
Of course, thanks!
