### ISSUE TITLE
Change representation of compound roles

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton-bib#6]
This ticket is part of the Relaton YAML refactor.

Roles are currently constructed through an array, consisting of either a single string (the role proper) or a pair of the role and an array of multiple descriptions of the role.

This is horrible to represent in YAML. Instead the representation of a single role should be a hash with keys type and description. If the representation is a single  string, that should be mapped to the tuple.

So the representation should be `[{type: "author", description: ["composer"]}]`, `[{type: "author", description: ["composer"]}, {type: "publisher", description: ["online distributor", "physical distributor"]]`. The initialiser should be able to deal with input like `["author"], ["author", "publisher"]`, by mapping it to `{type: ["author"]}`, `{type: ["author", "publisher"]}`. And the hash to biblio mapper needs to cope with input like `"author"`, by mapping it to `["author"]` (as it already done with all the other hash to biblio mappers I have written.)

**Comment by opoudjis** [comment]
You haven't pushed the code for this yet?

**Comment by andrew2net** [comment]
@opoudjis I see the representation is changed already. Didn't you do it?

**Comment by opoudjis** [comment]
Wait, I'm requesting a change in the initialisation, I don't believe an array is useful. (For direct YAML representation, as I've said, it's bad). But no, there is no code change in relaton-bib that I can see:

contribution_info.rb is still:

````
  class ContributorRole
....
    # @param type [String] allowed types "author", "editor",
    #   "cartographer", "publisher"
    # @param description [Array<String>]
    def initialize(*args)
      @type = args.fetch 0
      if type && !TYPES.include?(type)
        raise ArgumentError, %{Type "#{type}" is invalid.}
      end

      @description = args.fetch(1, []).map { |d| FormattedString.new content: d, format: nil }
    end
````

I've updated  `contributors_hash_to_bib(ret)` in the same file, but I have not touched the representation of roles.

**Comment by andrew2net** [comment]
@opoudjis seems I misunderstood the issue. Sorry. I'll combine the refactoring with #7

**Comment by opoudjis** [comment]
The YAML is meant to be able to pass a Hash into the role; that's the whole point of this. I am fixing this now.
