### ISSUE TITLE
Implement Relaton XML / YAML schema versioning

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-bib#62]
As per Relaton meeting 2022-10-09.

A relaton file (XML/YAML) contains two portions:
- generic Relaton content
- flavor-specific Relaton content

This task is to apply schema versioning to both parts.

The generic Relaton content version is (now) dictated by the version number here:
* https://github.com/relaton/relaton-models/releases

In YAML, it can be realized as:

```yaml
---
relaton-schema-version: 1.0
```

In XML, it can be realized as:

```xml
<relaton ... schema-version="1.0">
```

The flavor-specific Relaton content version depends on the flavor schema, which needs to split out for individual versioning, is dependent on this ticket:
* https://github.com/relaton/relaton-models/issues/43

We need to first split the schemas into repos, then version those schemas independently. The version number will then apply only to that potion of content.

**Comment by opoudjis** [comment]
This means adding optional "schema-version" attributes to both bibitem and bibitem/ext.

**Comment by opoudjis** [comment]
The contents of schema-version come from the version.json file which is now generated. https://github.com/relaton/relaton-models/issues/47

@andrew2net Once you populate those values into the published gems, you can close this ticket.
