### ISSUE TITLE
Generating anchors in AsciiBib

### ISSUE THREAD

**Issue by anermina** [relaton/relaton-bib#63]
According to https://www.metanorma.org/author/topics/document-format/bibliography/ the value of the `id` attribute of `bibitem` should be used as an anchor. However, the value of the `docid` attribute is used instead.

When adding an anchor as a `docid` attribute (`docid:: edge_mesh`), I get the following error:
````
C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/relaton-bib-1.13.9/lib/relaton_bib/hash_converter.rb:150:in `[]': no implicit conversion of Symbol into Integer (TypeError)
```` 

This is related to https://github.com/metanorma/SWF-Corpus_and_IEEEP2874-D2/issues/10.

@andrew2net could you please check?

**Comment by andrew2net** [comment]
The `docid` is an object. It should contain `type` and `id`. Other attributes are optional.
```
docid::
docid.type:: ISO
docid.scope:: series
docid.primary:: true
docid.language:: en
docid.script:: Latn
docid.id:: ISO TC 211
```

**Comment by anermina** [comment]
Thank you for @andrew2net. Closing this ticket.
