### ISSUE TITLE
Document generation crashes when using `extent` attribute

### ISSUE THREAD

**Issue by anermina** [relaton/relaton-bib#64]
When using `extent` attribute in `%bibitem`, reference doesn't get rendered and the generation of the document failes.

For example, following part of the code
````
extent::
  type::: volume
  reference_from::: 5
extent::
  type::: page
  reference_from::: 16441
  reference_to::: 16458
````

produces this error:
````
C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/relaton-bib-1.13.9/lib/relaton_bib/hash_converter.rb:67:in `locality': undefined method `[]' for nil:NilClass (NoMethodError)
````

This issue is related to https://github.com/metanorma/SWF-Corpus_and_IEEEP2874-D2/issues/10.

@andrew2net could you please check?

**Comment by andrew2net** [comment]
@anermina I think the example has the wrong format. It should use 2 colon, not 3
```
extent::
  type:: volume
  reference_from:: 5
extent::
  type:: page
  reference_from:: 16441
  reference_to:: 16458
```

**Comment by ronaldtse** [comment]
> It should use 2 colon, not 3

Whoa, I thought this is an AsciiDoc definition list that works like this?

```adoc
first-level:: first one
second-level::: second one
second-level::: second again
first-level:: first again
```

I'm confused. Does the additional whitespace matter?

**Comment by opoudjis** [comment]
The whitespace does not matter. @andrew2net is wrong: see

https://github.com/metanorma/metanorma-standoc/blob/main/spec/metanorma/biblio_spec.rb

**Comment by opoudjis** [comment]
Error reproduced:

````
Fatal Error: undefined method `[]' for nil:NilClass

          Locality.new(l[:type], l[:reference_from], l[:reference_to])
                        ^^^^^^^
undefined method `[]' for nil:NilClass

          Locality.new(l[:type], l[:reference_from], l[:reference_to])
                        ^^^^^^^
````

For some reason type is not propagating. When I get time, I'll confirm that I am passing it on.

**Comment by opoudjis** [comment]
Reminder: the span notation described in https://www.metanorma.org/author/topics/document-format/bibliography/#annotating-pre-formatted-citations-semantically involves less heart-ache

**Comment by opoudjis** [comment]
No, it's propagating correctly:

````
bib = {"id"=>"iso123",
 "docid"=>{"type"=>"ISO", "id"=>"ISO 123"},
 "type"=>"standard",
 "contributor"=>{"role"=>"publisher", "organization"=>{"name"=>"ISO"}},
 "extent"=>{"type"=>"volume", "reference_from"=>"5"},
 "title"=>["Standard"]}

RelatonBib::BibliographicItem.from_hash(bib)
````

is yielding the crash reported.

**Comment by opoudjis** [comment]
AAAARGH

@anermina, this is why I want you to use spans instead.

The extent is actually meant to be:

````
extent::
  locality:::
    type:::: volume
    reference_from:::: 5
````

I've neglected the locality wrapper in extent in the span code too.

**Comment by ronaldtse** [comment]
@opoudjis I really don't understand why there are indents made before the definition term. 

This is way too confusing. In a definition list only the number of colons matter.

**Comment by opoudjis** [comment]
Visual clarity, and I clearly saw someone else do that, but yes, the indent in nested definition lists is cosmetic, and is ignored by Asciidoctor.

**Comment by ronaldtse** [comment]
That's entirely an example of what not to do. AsciiDoc treats initial indents as quotation blocks. This unnecessary indent confuses the user what exactly is the key change is, and makes them question whether it is the additional indent or the colons that cause a second level definition list.

That's also why our editors missed the additional colon at the third level. Poorly defined grammar only gets more confusing with poorly demonstrated examples.
