### ISSUE TITLE
Do not hardcode locality types

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-bib#66]
https://github.com/relaton/relaton-bib/blob/d8031f228edcabeeb3998ad3a93de3f506c14da0/lib/relaton_bib/bib_item_locality.rb#L16-L27

The list of types should be dynamically generated, not hardcoded in a RegEx.

**Comment by andrew2net** [comment]
@ronaldtse the list of types is defined in the [schema](https://github.com/relaton/relaton-models/blob/3b419295fcdfd5c74f5d44998f6e56ed53750af3/grammars/biblio.rnc#L241). Do you mean we need to extract the list of types from the grammar?

**Comment by andrew2net** [comment]
Locality types are defined as a regex pattern in the [grammar](https://github.com/relaton/relaton-models/blob/0951d4243815cdd9123c2a7ec47e56ef353a1bb8/grammars/biblio.rng#L796). Relaton just use the pattern.
