### ISSUE TITLE
`[relaton-bib] WARNING: invalid relation type: instanceOf`

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-bib#79]
https://github.com/Spatial-Web-Foundation/SWF-Corpus_and_IEEEP2874-D2/actions/runs/6119622323/job/16609900402

Error message:
```
[relaton-bib] WARNING: invalid relation type: instanceOf
```

**Comment by andrew2net** [comment]
@ronaldtse the link doesn't work for me, I don't have permission. How to reproduce the issue?

**Comment by ronaldtse** [comment]
Try the fork in the metanorma GitHub account.

**Comment by andrew2net** [comment]
I didn't manage to run the `generate.sh` script without error. However, I got from the log that relaton v1.15.0 is used. We have changed the relation type from `instsnce` to `instanceOf` in relaton v1.16.0

**Comment by ronaldtse** [comment]
Got it, thanks!
