### ISSUE TITLE
Date corrected

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton-bib#81]
From https://github.com/metanorma/metanorma-iso/issues/1045

I have just added "corrected" as a possible type of date; it will be used for ISO documents at minimum, to distinguish it from date updated.

This `<date type="corrected">` will need to be recognised in the screenscraping of documents such as ISO/IEC 2382 ("Corrected version"):

https://www.iso.org/standard/63598.html

![Screenshot 2023-11-12 at 19 16 20](https://github.com/relaton/relaton-bib/assets/1911039/5d4e3dc5-c56f-4f66-9c30-2bb3f11c711f)

**Comment by andrew2net** [comment]
Fixed in relaton-bib v1.16.4, relaton-iso-bib v1.16.2, and relaton-iso v1.16.4
```sh
$ relaton fetch --no-cache 'ISO/IEC 2382:2015'
Resolving dependencies...
[relaton-iso] (ISO/IEC 2382:2015) Fetching from iso.org ...
[relaton-iso] (ISO/IEC 2382:2015) Found: `ISO/IEC 2382:2015`
<bibdata type="standard" schema-version="v1.2.5">
  ...
  <date type="published">
    <on>2015-05</on>
  </date>
  <date type="corrected">
    <on>2022-10</on>
  </date>
  ...
```
