### ISSUE TITLE
Add abbreviation to personal name

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton-bib#82]
Follow-on from https://github.com/metanorma/metanorma-bsi/issues/286:

The scope of "initials" in person names has been ambiguous. Initially, it was intended to include the surname, as a replacement for the complete name; but formatted-initials instead has become a replacement for given names, in bibliographic references.

We are back to requiring initials as an abbreviation of the entire name, because of the use of such initials in errata (which we will make draw on our model of contributors). We will represent them as contributor/person/name/abbreviation. So:

````
<contributor>
<person>
<name>
  <abbreviation>JMS</abbreviation>
  <forename>J.</forename>
  <forename>Michael</forename>
  <formatted-initials>J. M.</formatted-initials>
  <surname>Straczynski</surname>
</name>
</person>
</contributor>
````

**Comment by andrew2net** [comment]
@opoudjis there is an misspelling in [name_abbrevation](https://github.com/relaton/relaton-models/blob/e67838ffd26a0baaa34e60577f64e0ef03e5a1aa/grammars/biblio.rng#L272C1-L272C1)

**Comment by ronaldtse** [comment]
> @opoudjis there is an misspelling in [name_abbrevation](https://github.com/relaton/relaton-models/blob/e67838ffd26a0baaa34e60577f64e0ef03e5a1aa/grammars/biblio.rng#L272C1-L272C1)

Fixed in https://github.com/relaton/relaton-models/pull/51

**Comment by opoudjis** [comment]
The fix done here does not quite work:

````
FullNameType =
    name_abbreviation?,
    (( prefix*, forename*, formatted-initials?, surname, addition* ) | completeName ),
    biblionote*, variantname*
````

This markup allows:

````
person:
  name: 
     completename: Fred Flintstone
     abbreviation: FF
````

**Comment by andrew2net** [comment]
> The fix done here does not quite work:

@opoudjis I didn't get what the problem is. Could you explain?

**Comment by opoudjis** [comment]
I'm sorry, false alarm, the problem was elsewhere. I thought you weren't parsing the combination of completename + abbreviation, but you are.
